### PR TITLE
add script to rename files recursively

### LINKED ISSUE #2: Create a Bash script to recursively rename files and folders
> in the README.md, under get **Get started** section
> >Clone this RN 0.70.0 starter project and replace the word "lilac" with your project name everywhere. Rename Folders having word "lilc" with you project name.
>
> I would like to automate this

Create a Bash script that can search recursively into a directory and find files/folder names with any word (say "XYZ"), and replace that word in the file/folder name with another word (say "ABC")

for example

If the file structure looks like this
```
rootDir/
  |_____FileXYZ.txt
  |_____File.js
  |_____XYZFile.tsx
  |_____FolderA
  |           |_____FileXYZ.txt
  |           |_____File.txt
  |           |_____XYZFile.txt
  |           |_____XYZFolder
  |               
  |_____FolderXYZaaa
  |                |_____XYZFile.txt
  |                |_____XYZFolder
  |_____FolderXYZ

```

then after running the bash script in `rootDir/`
the files/folder with word XYZ will with get replaced with ABC
so finally the files and folder will looks something like this:

```
rootDir/
  |_____FileABC.txt
  |_____File.js
  |_____ABCFile.tsx
  |_____FolderA
  |           |_____FileABC.txt
  |           |_____File.txt
  |           |_____ABCFile.txt
  |           |_____ABCFolder
  |               
  |_____FolderABCaaa
  |                |_____ABCFile.txt
  |                |_____ABCFolder
  |_____FolderABC

```

### PR DESCRIPTION
**Pull request by nkilm**
#### Before 
before

#### After renaming
after

NOTE: `test.sh` and `rename-files.sh` are same files, I renamed it later.

### CODE REVIEW

**Comment by ashuvssut** [comment]
@nkilm I found a issue with your script. If you want to fix it, you can read up issue #4 to  know about that.

Thanks for you contribution!

**Comment by nkilm** [comment]
@ashuvssut To fix #4 what we can do is include directories also in addition to files. i.e, `find . -type d -name query`. 

For files, `-type f` and directories `-type d`

**Comment by ashuvssut** [comment]
> For files, -type f and directories -type d

@nkilm thanks man! now the script's working fine

**Comment by nkilm** [comment]
@ashuvssut Happy to help!

**Pull request merged**
